### ISSUE TITLE
add initial structure of README

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-cg/awesome-semantic-shapes#1]
@amivanoff could you please take a first stab at it? 
Make the structure as per `awesomelists` (https://github.com/w3c/shacl/issues/78#issuecomment-2309745899) and add sections as per my above comment and the "updated list".

**Comment by amivanoff** [comment]
Ok, on it

**Comment by amivanoff** [comment]
After some initial screening of [Updated list of implementations](https://github.com/validatingrdf/validatingrdf.github.io/wiki/Updated-list-of-implementations) I may conclude, it needs to decide upfront (and document in CONTRIBUTING.md maybe) on software inclusion/exclusion criteria:
- What to do with "abandonware" (5-6 years old from last update)?
- What to do with "unusable prototypes"? Especially in section "Shape Editors, Visualizations" :) Something like "is cool-looking but unusable -- awesome, or not"; “is novice, but not cool-looking and not usable -- awesome, or not”

Because there are too much of it in SemWeb area and both cases exist even in "Updated list of implementations".

Do we need a criterion “I propose it to the “awesome” because I really using it” or not?

And also, are we including open-source only or closed-source too? If so, it seems, we need OSS/$$$ mark on every software entry.

**Comment by amivanoff** [comment]
I also could commit settings for VS Code with "Markdown All in One" and spellchecker with recommend extensions, initial dictionary and so on, if we agree on common IDE.

**Comment by tpluscode** [comment]
> 1 What to do with "abandonware" (5-6 years old from the last update, or more)?

Fine if it is known to work. But we could add some marker for software which hasn't received updates in a long time. Like "☠️☠️☠️", or something less loaded

> 2 What to do with "unusable prototypes" [...]

That's a hard one. Some software may have a narrow use case but do it's job. Some are developed with little resources and an awesome-list can boost visibility. I would not try to be too restrictive because in the end you rely on arbitrary decisions.

> 3 Are we including open-source only or closed-source too?

+1 to closed/commercial too.
+1 to a 💰💰💰 marker

> 4 Should we sort software in categories by its name or by popularity?

Name IMO. Else, how do you decide on popularity? GitHub stars, package repository download count? Would someone keep the ordering in sync with changes to popularity?

> if we agree on common IDE

One should never do that IMO. VS Code may be popular but it's not the only tool. And expect contributions directly from GitHub. All formatting, linting, spellchecking should be IDE-agnostic and runnable from the command line.

**Comment by amivanoff** [comment]
> One should never do that IMO. VS Code may be popular but it's not the only tool. And expect contributions directly from GitHub. All formatting, linting, spellchecking should be IDE-agnostic and runnable from the command line.

IDE-agnostic CLI tools just for one file -- It looks like overkill. It also requires some stack commitment: Java one (Maven/Gradle) or JS (ESLint, etc) or any other...

**Comment by VladimirAlexiev** [comment]
@amivanoff , thanks for your PR!! I made some comments.

In general I agree with @tpluscode :
- let's be inclusive. Even if something appears dead, if it's promising, someone may revive it
- I like adding icons
- I would really like to have the last updated date and version. I understand these will get obsolete very soon, but still a sofware updated 5y ago is very different from one updated 1 month ago.
- number of contributors, stars and forks is also important info, would be nice to have
- IMHO it's ok to add substantive comments, even though these are subjective.
Eg "tried it, can't compile"
or "Shaclex is the only implementation of SHACL **and** ShEx"
- Within big sections, let's have subsections per language: Java, Python, JS. This is a major constraint on selecting a software
- Let's list the most important software first in a section. 
Eg for Java that's Jena, Rdf4j, TQ, Shaclex.
For the less established sections, any order will do.

Last but not least:
- https://index.semanticscience.org/ is a treasure trove: 4.5k repos with SHACL, we need to explore them
- How do you call these? Guess we need a new section "Shape Extensions"?
  - https://index.semanticscience.org/
  - https://shape-fragments.github.io/shape-fragments-spec/

**Comment by VladimirAlexiev** [comment]
Can you add JS implementatons from https://github.com/w3c/shacl/issues/78#issuecomment-2354996813

**Comment by tpluscode** [comment]
> * I would really like to have the last updated date and version. I understand these will get obsolete very soon, but still a sofware updated 5y ago is very different from one updated 1 month ago.
> * number of contributors, stars and forks is also important info, would be nice to have

I like those ideas but I don't see this would be possible without actually generating the list and sourcing some of this information from GitHub directly. Else, as you said, it'd immediately become out of date

**Comment by amivanoff** [comment]
To indicate the _last commit activity_ we could use bages from https://img.shields.io like here https://github.com/awesome-spark/awesome-spark

There are similar color-coded bages there for the [GitHub Releases Date](https://shields.io/badges/git-hub-release-date) and for the version from the Releases

**Comment by amivanoff** [comment]
Release or Tag -- always blue, Release date or Last commit -- color-coded.

**Comment by amivanoff** [comment]
License and programming language formatting example [awesome-selfhosted/awesome-selfhosted](https://github.com/awesome-selfhosted/awesome-selfhosted)

**Comment by VladimirAlexiev** [comment]
More for "last but not least "
 https://github.com/hypermedia-app/shape-to-query 
 https://shape-to-query.hypermedia.app/docs/#extension-spo-rule

**Comment by VladimirAlexiev** [comment]
[shacl-maven-plugin](https://github.com/qudtlib/shacl-maven-plugin): supports validation and inferencing. I guess it serves to process RDF files in a source code repo, as it's mentioned in https://github.com/qudt/qudt-public-repo/issues/959

**Comment by TallTed** [comment]
> * Let's list the most important software first in a section
>   Eg for Java that's Jena, Rdf4j, TQ, Shaclex.

I think "the most important software" is an extremely subjective ordering.

I also wonder about "server" vs "client" in that "Java" section. Java "client" tools that use, for instance, JDBC or HTTP to connect to "servers" may (I daresay, should) not care about the runtime that "server" is running in (JRE, Intel-native [macOS, Linux, Windows, other?], ARM-native [macOS, Linux, other?], etc.)
